name: Deploy Proxy Server to Google Cloud Functions on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v0.1.0
        with:
          name: apiProxy
          runtime: nodejs14
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCF_SA_KEY }}
